### ISSUE TITLE
Asphyxia.lua:774: attempt to index field 'panel' (a nil value)

### ISSUE THREAD

**Issue by ghost** [sinaris/AsphyxiaUI---v6#1]
Message: ...ce\AddOns\AsphyxiaUI\Unitframes\Layouts\Asphyxia.lua:774: attempt to index field 'panel' (a nil value)
Time: 09/01/12 13:23:15
Count: 1
Stack: ...ce\AddOns\AsphyxiaUI\Unitframes\Layouts\Asphyxia.lua:774: in main chunk

Locals: S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2405
 resolution = "1400x1050"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 28.777517564403
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1028
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:39
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:104
 screenwidth = 1400
 MicroMenu = <table> {
 }
 lowversion = true
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\AddOns\AsphyxiaUI\Media\Fonts\Asphyxia.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1011
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C]:-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:121
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:44
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 buffids = <table> {
 }
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:41
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:61
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 DruidBarDisplay = <function> defined =[C]:-1
 buttonspacing = 3.5971896955504
 SkinSlideBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:630
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:663
 SetDefaultActionButtonCooldownMinDuration = 2.5
 UpdateThreat = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1064
 HidePortrait = <function> defined @Interface\AddOns\Tukui\core\functions.lua:769
 healfilter = <table> {
 }
 PostUpdateHealthRaid = <function> defined =[C]:-1
 SkinFuncs = <table> {
 }
 UpdateName = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1005
 SkinTab = <function> defined @Interface\AddOns\Tukui\core\api.lua:476
 SkinRotateButton = <function> defined @Interface\AddOns\Tukui\core\api.lua:531
 IsPTRVersion = <function> defined @Interface\AddOns\Tukui\core\functions.lua:10
 SkinScrollBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:404
 client = "deDE"
 createAuraWatch = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1113
 build = 16016
 RGBToHex = <function> defined @Interface\AddOns\Tukui\core\functions.lua:234
 PostUpdatePower = <function> defined @Interface\AddOns\Tukui\core\functions.lua:556
 StyleShift = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:143
 fadeIn = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:63
 SkinCheckBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:583
 fadeOut = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:58
 countOffsets = <table> {
 }
 SetFontString = <function> defined @Interface\AddOns\Tukui\core\functions.lua:19
 Scale = <function> defined @Interface\AddOns\Tukui\core\api.lua:24
 PostUpdateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:713
 DataTextPosition = <function> defined @Interface\AddOns\Tukui\core\functions.lua:

**Comment by sinaris** [comment]
This error occurs if you have low reso or no target of target enabled.
I will implement some fixes for that with the next update.

**Comment by sinaris** [comment]
Enable the highresolution layout if you are using a lowresolution screen.
This will fix this error.
