### ISSUE TITLE
Spell Interrupt - Typo fix silly Sinaris

### ISSUE THREAD

**Issue by Slapaxx** [sinaris/AsphyxiaUI---v6#10]
Date: 2012-09-13 22:57:38
ID: -3
Error occured in: Global
Count: 2
Message: ...face\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua line 822:
   attempt to concatenate global 'ACTION_SPELL_INTERRUPS' (a nil value)
Debug:

   ...face\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:822:
      ...face\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:679
Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
msg = " "
icon = "Interface\Icons\Spell_Holy_SearingLight"
timestamp = 1347595071.153
eventType = "SPELL_INTERRUPT"
hideCaster = false
sourceGUID = "0x02000000063ADEA8"
sourceName = "Slapaxx"
sourceFlags = 1297
srcFlags2 = 0
destGUID = "0xF130BD220001700F"
destName = "Defias Envoker"
destFlags = 68168
destFlags2 = 0
target = 47528
_ = "Mind Freeze"
_ = 16
id = 91004
effect = "Holy Fire"
color = <table> {
 1 = 1
 2 = 0.5
 3 = 0
}
(_temporary) = <function> defined =[C](?):-1
(_temporary) = xCT3 {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = ": Holy Fire "
(_temporary) = "Holy Fire"
(_temporary) = " "
(_temporary) = ":0:0:64:64:5:59:5:59"
(_temporary) = 47528
(_temporary) = "Mind Freeze"
(_temporary) = 16
(_temporary) = 91004
(_temporary) = "Holy Fire"
(_temporary) = 4
(_temporary) = "attempt to concatenate global 'ACTION_SPELL_INTERRUPS' (a nil value)"
select = <function> defined =[C](?):-1
ct = <table> {
 justify_2 = "RIGHT"
 dmgcolor = <table> {
 }
 blank = "Interface\AddOns\ShestakUI\Media\Textures\Blank.tga"
 frames = <table> {
 }
 unit = "player"
 pguid = "0x02000000063ADEA8"
 SpamQueue = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:621
 locked = true
 justify_4 = "RIGHT"
 justify_3 = "CENTER"
 justify_1 = "LEFT"
}
C = <table> {
 databars = <table> {
 }
 merchant = <table> {
 }
 general = <table> {
 }
 media = <table> {
 }
 combattext = <table> {
 }
 bags = <table> {
 }
 datatext = <table> {
 }
 auras = <table> {
 }
 loot = <table> {
 }
 global = <table> {
 }
 castbar = <table> {
 }
 tooltip = <table> {
 }
 intmodules = <table> {
 }
 invite = <table> {
 }
 raidcooldowns = <table> {
 }
 nameplate = <table> {
 }
 addonskins = <table> {
 }
 actionbar = <table> {
 }
 unitframes = <table> {
 }
 error = <table> {
 }
 cooldown = <table> {
 }
 chat = <table> {
 }
}
gflags = 8465
S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2409
 resolution = "1920x1200"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:988
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:62
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 CheckCast = <function> defined =[C](?):-1
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\AddOns\AsphyxiaUI\Media\Fonts\Asphyxia.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:971
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C](?):-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:124
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:49
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 GetAsphyxiaUIVersion = "6.0.311"
 SkinDropDownBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:560
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:44
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:66
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 ShowPopup = <func
AddOns:
  Swatter, v5.15.5340 (LikeableLyrebird)

**Comment by sinaris** [comment]
Thanks. Fixed now.
https://github.com/sinaris/AsphyxiaUI---v6/commit/047c6cea08e26cbcccd950dd351e389e5d5f9bb1
