### ISSUE TITLE
CombatText.lua

### ISSUE THREAD

**Issue by Shestak** [sinaris/AsphyxiaUI---v6#18]
I do not understand, you're ignoring me?
I wrote a commit that would write Credits in the CombatText.lua, but you do not want to do hard.
https://github.com/sinaris/AsphyxiaUI---v6/commit/dddf37c0e915848e4c93f674cef083c63b2b6df2#asphyxiaui-modules-extras-combattext-lua-P673

This is xCT by Affli.

P.S.: Respect the work of the authors.

**Comment by Hydrazine** [comment]
+1 Shestak

**Comment by Slapaxx** [comment]
I am so with you there Shestak damn i'm adding credits to the file i'm using of this now just so i feel better about using it.

**Comment by sinaris** [comment]
Added the missing credits the authors. Was my fault, sorry :(

https://github.com/sinaris/AsphyxiaUI---v6/commit/bbac54c3bfb011e16f720c6059e6ce1577ca5231
