### ISSUE TITLE
Skinning Issue

### ISSUE THREAD

**Issue by Elegant996** [sinaris/AsphyxiaUI---v6#24]
While using TukUI & ElvUI Extra Skins addon, even if the addon has it's skins for DBM/Skada/Recount/TinyDPS/etc. disabled, AsphyxiaUI wishes to disable it's own skins of DBM/Skada/Recount/TinyDPS/etc. despite the fact that nothing is currently skinning those other addons.

Thus a popup appears each login asking to disable the Asphyxia UI skins.

**Comment by sinaris** [comment]
This has been fixed a long time. Please update to the latest version.

**Comment by Elegant996** [comment]
Did so, now I can see that it's disabling the other addon entirely instead of selective skins.

More or less the UI is now forcing me to disable all the skins it has or all the skins the other one has (by disabling the addon). What I want is a combination of the 2 which the addon used to do.

This used to work with an older version of the addon, I guess they broke how it interacted with others' UI.

In the mean time I'll just comment out the popup entirely ;)
