### ISSUE TITLE
Nameplates Bug

### ISSUE THREAD

**Issue by Elegant996** [sinaris/AsphyxiaUI---v6#25]
Ticking Enable Nameplates and reloading the UI forces a blank Accept/Cancel box to appear.

Hitting Accept disables the AsphyxiaUI nameplates and restores the TukUI default (forcible unticks  the Enable Namplates).

Hitting Cancel allows the Asphyxia UI nameplates to be used but causes the same Pop Up window to occur each log in.

**Comment by sinaris** [comment]
fixed.
https://github.com/sinaris/AsphyxiaUI---v6/commit/6297d03d8b6cee341ed69270b658f9334d2870e5
