### ISSUE TITLE
UnitFrame's layouts 'maxHolyPower' variable typo

### ISSUE THREAD

**Issue by seigert-xx** [sinaris/AsphyxiaUI---v6#26]
At least in 'asphyxia' and 'asphyxia2' UF layouts there is a typo in `maxHolyPower` variable: around lines 310-314 it is written as `maxHolypower`, which causes LUA errors:

``` lua
                local maxHolyPower
                if( S.level == MAX_PLAYER_LEVEL ) then
                    maxHolypower = 5
                else
                    maxHolyPower = 3
                end
```

**Comment by sinaris** [comment]
fixed.
https://github.com/sinaris/AsphyxiaUI---v6/commit/7eddd470599f9d4469943613c922dd476741fdb8
