### ISSUE TITLE
Nameplates Bug (Again)

### ISSUE THREAD

**Issue by Elegant996** [sinaris/AsphyxiaUI---v6#29]
I'll post screenshots again of what's happening.

http://imgur.com/XvWHa

I now tick the box and click apply causing a UI reload.

http://imgur.com/E1Erp

I now click accept so that the tukui nameplates (which don't appear to be enabled) be disabled.

http://imgur.com/a2RyS

And now the nameplates are disabled? Problem.

**Comment by sinaris** [comment]
Okay. I dont know what an error you mean. There are two nameplate that you can use.
You can use the default tukui nameplates or you can use the asphyxia nameplates.

Tukui nameplates: 
/tc -> Nameplates -> uncheck all options and only enable: Enable Nameplates _red warning text_

AsphyxiaUI nameplates:
/tc -> Nameplates -> Uncheck all options and enable: 
Enable AsphyxiaUI nameplates

If you dont want to have any of them disable all options and you can use another nameplate addons as well.

**Comment by Elegant996** [comment]
Ah, I was probably not explaining myself too well there I think.

The issue is if I want to use the TukUI nameplates your popup keeps showing up each login asking to disable them and activate the AsphyxiaUI nameplates. I hit Cancel but then next login your UI asks again. I simply want to leave the TukUI nameplates active without the need of hitting cancel each login.

Also I did set it up as you suggested:
/tc -> Nameplates -> uncheck all options and only enable: Enable Nameplates red warning text

**Comment by sinaris** [comment]
Ah. Okay. I will implement a fix for this.
