### ISSUE TITLE
Another Bug story's...

### ISSUE THREAD

**Issue by Bloodb** [sinaris/AsphyxiaUI---v6#31]
Message: ...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:79: attempt to call field 'CreateFontString' (a nil value)
Time: 09/20/12 20:52:57
Count: 2
Stack: ...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:79: in function <...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:77>
...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:164: in function <...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:138>
...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:182: in function <...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:175>
...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:218: in function <...e\AddOns\AsphyxiaUI\Modules\Extras\RaidCooldowns.lua:210>

Locals: frame = <unnamed> {
 0 = <userdata>
 status = <unnamed> {
 }
 bg = <unnamed> {
 }
 icon = <unnamed> {
 }
}
fsize = nil
fstyle = nil
fstring = <unnamed> {
 0 = <userdata>
}
(_temporary) = <function> defined =[C]:-1
(_temporary) = <unnamed> {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = "attempt to call field 'CreateFontString' (a nil value)"
S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2415
 resolution = "1920x1080"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:988
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:62
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 CheckCast = <function> defined @Interface\AddOns\Tukui\core\functions.lua:801
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\Addons\Tukui\medias\fonts\normal_font.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:971
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C]:-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:124
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:47
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 GetAsphyxiaUIVersion = "6.0.311"
 SkinDropDownBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:560
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:44
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:64
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 ShowPopup = <function> defined @Interface\AddOns\Tukui\core\popup.lua:84
 buttonspacing = 4
 SkinSlideBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:629
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:663
 buildtext = "16057"
 UpdateThreat = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1024
 HidePortrait = <function> defined @Interface\AddOns\Tukui\core\functions.lua:769
 SetGridGroupRole = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1043
 healfilter = <table> {
 }
 PostUpdateHealthRaid = <function> defined =[C]:-1
 SkinFuncs = <table> {
 }
 UpdateName = <function> defined @Interface\AddOns\Tukui\core\functions.lua:965
 SkinTab = <function> defined @Interface\AddOns\Tukui\core\api.lua:475
 SkinRotateButton = <function> defined @Interface\AddOns\Tukui\core\api.lua:530
 IsPTRVersion = <function> defined @Interface\AddOns\Tukui\core\functions.lua:10
 SkinScrollBar = <funct

**Comment by sinaris** [comment]
GetAsphyxiaUIVersion = "6.0.311"

You are using an outdated version. Please update your AsphyxiaUI installation.
