### ISSUE TITLE
2unitframes active

### ISSUE THREAD

**Issue by Raecius** [sinaris/AsphyxiaUI---v6#32]
Just did a fresh install of tukui and asphyxia ui, but there are currently 2 unitframes active. While in /tc i stated i wanted asphyxia5

Message: ...AsphyxiaUI\Unitframes\Layouts\Asphyxia\Asphyxia5.lua:316: 'for' limit must be a number
Time: Sun Sep 23 11:47:13 2012
Count: 1
Stack: ...AsphyxiaUI\Unitframes\Layouts\Asphyxia\Asphyxia5.lua:316: in main chunk

Locals: S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2415
 resolution = "1920x1200"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:988
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:62
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 CheckCast = <function> defined =[C]:-1
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\AddOns\AsphyxiaUI\Media\Fonts\Asphyxia.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:971
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C]:-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:124
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:49
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 GetAsphyxiaUIVersion = "6.0.483"
 SkinDropDownBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:560
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:44
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:66
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 ShowPopup = <function> defined @Interface\AddOns\Tukui\core\popup.lua:84
 buttonspacing = 4
 SkinSlideBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:629
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:663
 buildtext = "16057"
 UpdateThreat = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1024
 HidePortrait = <function> defined @Interface\AddOns\Tukui\core\functions.lua:769
 SetGridGroupRole = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1043
 healfilter = <table> {
 }
 PostUpdateHealthRaid = <function> defined =[C]:-1
 SkinFuncs = <table> {
 }
 UpdateName = <function> defined @Interface\AddOns\Tukui\core\functions.lua:965
 SkinTab = <function> defined @Interface\AddOns\Tukui\core\api.lua:475
 SkinRotateButton = <function> defined @Interface\AddOns\Tukui\core\api.lua:530
 IsPTRVersion = <function> defined @Interface\AddOns\Tukui\core\functions.lua:10
 SkinScrollBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:403
 client = "enUS"
 createAuraWatch = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1092
 build = 16057
 RGBToHex = <function> defined @Interface\AddOns\Tukui\core\functions.lua:234
 PostUpdatePower = <function> defined =[C]:-1
 UTF = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:12
 StyleShift = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:141
 fadeIn = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:86
 SkinEditBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:547
 fadeOut = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:81
 countOffsets = <table> {
 }
 SetFontString = <function> defined @Interface\AddOns\Tukui\core\functions.lua:19
 Scale = <function> defined @Interface\Ad

**Comment by sinaris** [comment]
Its already fixed.
https://github.com/sinaris/AsphyxiaUI---v6/commit/7eddd470599f9d4469943613c922dd476741fdb8
