### ISSUE TITLE
Player Unitframe Mouse over Symbiosis error

### ISSUE THREAD

**Issue by Feraldps** [sinaris/AsphyxiaUI---v6#33]
Message: ...face\AddOns\AsphyxiaUI\Modules\Tooltip\Symbiosis.lua:54: attempt to index field '?' (a nil value)
Time: 09/26/12 14:06:04
Count: 3
Stack: ...face\AddOns\AsphyxiaUI\Modules\Tooltip\Symbiosis.lua:54: in function <...face\AddOns\AsphyxiaUI\Modules\Tooltip\Symbiosis.lua:38>

[C](?): in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:224: in function`UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:211: in function `UnitFrame_OnEnter'
...ce\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:902: in function <...ce\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:896>

Locals: self = GameTooltip {
 0 = <userdata>
 insettop = <unnamed> {
 }
 shoppingTooltips = <table> {
 }
 insetbottom = <unnamed> {
 }
 Anchor = TukuiTooltipAnchor {
 }
 insetinsidebottom = <unnamed> {
 }
 isInsetDone = true
 comparing = false
 insetinsideleft = <unnamed> {
 }
 default = 1
 SetUnitAura = <function> defined =[C](?):-1
 SetUnitDebuff = <function> defined =[C](?):-1
 updateTooltip = 0.16899999771267
 Health = GameTooltipStatusBar {
 }
 insetright = <unnamed> {
 }
 SetUnitBuff = <function> defined =[C](?):-1
 insetinsideright = <unnamed> {
 }
 insetinsidetop = <unnamed> {
 }
 insetleft = <unnamed> {
 }
}
unit = "player"
uclass = "DRUID"
ulevel = 87
uspec = 2
spec = "DRUID_FERAL"
spellID = nil
(_temporary) = nil
(_temporary) = "DRUID"
(_temporary) = "Feral"
(_temporary) = "Takes on the form of a great cat to deal damage with bleeds and bites."
(_temporary) = "Interface\Icons\Ability_Druid_CatForm"
(_temporary) = "bg-druid-cat"
(_temporary) = "DAMAGER"
(_temporary) = "attempt to index field '?' (a nil value)"
S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2415
 resolution = "1920x1080"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:988
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:62
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 CheckCast = <function> defined =[C](?):-1
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\AddOns\AsphyxiaUI\Media\Fonts\Asphyxia.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:971
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C](?):-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:124
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:49
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 GetAsphyxiaUIVersion = "6.0.483"
 SkinDropDownBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:560
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:44
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Asphyxia\Style.lua:66
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 ShowPopup = <function> defined @Interface\AddOns\Tukui\core\popup.lua:84
 buttonspacing = 4
 SkinSlideBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:629
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:663
 buildtext = "16057"
 UpdateThreat = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1024
 HidePortrait = <function> defined @Interface\Add

I get this when mousing over My player unitfram and when targeting myself and mousing over target unit frame.

**Comment by Feraldps** [comment]
For now I have just disabled "Show the ability you get from Symbiosis" under Tooltip options to make the error stop.

**Comment by sinaris** [comment]
fixed.
https://github.com/sinaris/AsphyxiaUI---v6/commit/140db71ee66e17d437704061399faeffc4b223a2
