### ISSUE TITLE
Major flaw in DK's layouts 

### ISSUE THREAD

**Issue by Slapaxx** [sinaris/AsphyxiaUI---v6#6]
Date: 2012-09-12 02:08:26
ID: -2
Error occured in: Global
Count: 1
Message: ...e\AddOns\AsphyxiaUI\Unitframes\Layouts\Asphyxia4.lua line 369:
   attempt to index field 'Statue' (a nil value)
Debug:

   ...e\AddOns\AsphyxiaUI\Unitframes\Layouts\Asphyxia4.lua:369: in main chunk
Locals:
S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2427
 resolution = "1920x1200"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1028
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:62
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 CheckCast = <function> defined @Interface\AddOns\Tukui\core\functions.lua:801
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\Addons\Tukui\medias\fonts\normal_font.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1011
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C](?):-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:124
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:47
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 GetAsphyxiaUIVersion = "6.0.311"
 buffids = <table> {
 }
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:44
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:64
 PostUpdatePetColor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:522
 ShowPopup = <function> defined @Interface\AddOns\Tukui\core\popup.lua:84
 buttonspacing = 4
 SkinSlideBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:629
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:663
 buildtext = "16048"
 UpdateThreat = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1064
 HidePortrait = <function> defined @Interface\AddOns\Tukui\core\functions.lua:769
 healfilter = <table> {
 }
 PostUpdateHealthRaid = <function> defined =[C](?):-1
 SkinFuncs = <table> {
 }
 UpdateName = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1005
 SkinTab = <function> defined @Interface\AddOns\Tukui\core\api.lua:475
 SkinRotateButton = <function> defined @Interface\AddOns\Tukui\core\api.lua:530
 IsPTRVersion = <function> defined @Interface\AddOns\Tukui\core\functions.lua:10
 SkinScrollBar = <function> defined @Interface\AddOns\Tukui\core\api.lua:403
 client = "enUS"
 createAuraWatch = <function> defined @Interface\AddOns\Tukui\core\functions.lua:1113
 build = 16048
 RGBToHex = <function> defined @Interface\AddOns\Tukui\core\functions.lua:234
 PostUpdatePower = <function> defined @Interface\AddOns\Tukui\core\functions.lua:556
 UTF = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:12
 StyleShift = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:141
 fadeIn = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:86
 SkinEditBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:547
 fadeOut = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:81
 countOffsets = <table> {
 }
 SetFontString = <function> defined @Interface\AddOns\Tukui\core\functions.lua:19
 Scale = <function> defined @Interface\AddOns\Tukui\core\api.lua:24
 PostUpdateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:713
 DataTextPosition = <function> defined @Interface\AddOns\Tukui\core\functions.lua:29
 MoveUIElements = <function> defined @Interface\AddOns\Tukui\core\move.lua:110
 StylePet = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:151
 level = 85
 update_alpha = <function> def
AddOns:
  AsphyxiaUI, v6.0.311
  AsphyxiaUIConfig, v6.0.311
  Tukui, v15.13
  TukuiConfigUI, v
  BlizRuntimeLib_enUS v5.0.5.50001 <us>
  (ck=174)

Remove this code from all layouts under the Death Knight class code:
                                G.UnitFrames.Player.Statue:ClearAllPoints()
                G.UnitFrames.Player.Statue:Size( 243, 2 )
                G.UnitFrames.Player.Statue:Point( "TOPRIGHT", G.UnitFrames.Player.Power, "BOTTOMRIGHT", 0, -7 )
                G.UnitFrames.Player.Statue:CreateBackdrop( "Default" )
                G.UnitFrames.Player.Statue.backdrop:CreateShadow( "Default" )

**Comment by sinaris** [comment]
You don't have the latest Tukui version installed.
Tukz implemented the StatueBar for some classes.

Please update to the latest Tukui and the error will be gone.

**Comment by Slapaxx** [comment]
Ahh thats why Hydra and i were boggled by this because he thought Tuk's did and i failed to update that version lik e i thought i did. Sorry about that.

**Comment by sinaris** [comment]
you're welcome.
If you have any other issue feel free to create a new ticket

**Comment by Slapaxx** [comment]
Hehe well when Tukz gets his site back up i'll update to his latest version and let you know =(

**Comment by sinaris** [comment]
Okay. i reopen the ticket.
Let me know if everthing works fine. If so, i will close the ticket again :)

**Comment by Slapaxx** [comment]
Finally got Tukz update just a bit ago, it is working great so far =)
