### ISSUE TITLE
Bug with UI

### ISSUE THREAD

**Issue by Bloodb** [sinaris/AsphyxiaUI---v6#9]
Message: ...face\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:819: attempt to concatenate global 'ACTION_SPELL_INTERRUPS' (a nil value)
Time: 09/13/12 22:09:08
Count: 1
Stack: ...face\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:819: in function <...face\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:676>

Locals: self = <unnamed> {
 0 = <userdata>
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
msg = " "
icon = "Interface\Icons\Spell_Frost_FrostBolt02"
timestamp = 1347566952.624
eventType = "SPELL_INTERRUPT"
hideCaster = false
sourceGUID = "0x06800000031CCDE8"
sourceName = "Njoytheblood"
sourceFlags = 1297
srcFlags2 = 0
destGUID = "0xF130E1CF000078B9"
destName = "Twilight Frost Evoker"
destFlags = 68168
destFlags2 = 0
target = 96231
_ = "Rebuke"
_ = 1
id = 109334
effect = "Frostbolt"
color = <table> {
 1 = 1
 2 = 0.5
 3 = 0
}
(_temporary) = <function> defined =[C]:-1
(_temporary) = xCT3 {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = ": Frostbolt "
(_temporary) = "Frostbolt"
(_temporary) = " "
(_temporary) = ":0:0:64:64:5:59:5:59"
(_temporary) = 96231
(_temporary) = "Rebuke"
(_temporary) = 1
(_temporary) = 109334
(_temporary) = "Frostbolt"
(_temporary) = 16
(_temporary) = "attempt to concatenate global 'ACTION_SPELL_INTERRUPS' (a nil value)"
select = <function> defined =[C]:-1
ct = <table> {
 justify_2 = "RIGHT"
 dmgcolor = <table> {
 }
 blank = "Interface\AddOns\ShestakUI\Media\Textures\Blank.tga"
 frames = <table> {
 }
 unit = "player"
 pguid = "0x06800000031CCDE8"
 SpamQueue = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Extras\CombatText.lua:618
 locked = true
 justify_4 = "RIGHT"
 justify_3 = "CENTER"
 justify_1 = "LEFT"
}
C = <table> {
 databars = <table> {
 }
 merchant = <table> {
 }
 general = <table> {
 }
 media = <table> {
 }
 combattext = <table> {
 }
 bags = <table> {
 }
 datatext = <table> {
 }
 auras = <table> {
 }
 loot = <table> {
 }
 global = <table> {
 }
 castbar = <table> {
 }
 tooltip = <table> {
 }
 intmodules = <table> {
 }
 invite = <table> {
 }
 raidcooldowns = <table> {
 }
 nameplate = <table> {
 }
 addonskins = <table> {
 }
 actionbar = <table> {
 }
 unitframes = <table> {
 }
 error = <table> {
 }
 cooldown = <table> {
 }
 chat = <table> {
 }
}
gflags = 8465
S = <table> {
 RaidFramePetAttributes = <function> defined @Interface\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:2409
 resolution = "1920x1080"
 dummy = <function> defined @Interface\AddOns\Tukui\core\init.lua:27
 petbuttonsize = 29
 UpdateDruidManaText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:988
 DataBarTooltipAnchor = <function> defined @Interface\AddOns\AsphyxiaUI\Core\Functions.lua:39
 StyleActionBarPetAndShiftButton = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:102
 screenwidth = 1920
 MicroMenu = <table> {
 }
 ShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:117
 PetBarUpdate = <function> defined @Interface\AddOns\Tukui\core\functions.lua:160
 SetDefaultActionButtonCooldownFont = "Interface\AddOns\AsphyxiaUI\Media\Fonts\Asphyxia.ttf"
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:971
 AllowFrameMoving = <table> {
 }
 UpdateMushroomVisibility = <function> defined =[C]:-1
 UnitColor = <table> {
 }
 ShortValue = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:121
 MoveUnitFrames = <function> defined @Interface\AddOns\Tukui\modules\unitframes\plugins\oUF_MovableFrames\movable.lua:534
 ShowHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaUI\Modules\Actionbars\Style.lua:44
 ColorTemplate = <table> {
 }
 Credits = <table> {
 }
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:380
 SkinDropDownBox = <function> defined @Interface\AddOns\Tukui\core\api.lua:560
 PostCastStart = <function> defined @Interface\AddOns\AsphyxiaUI\Unitframes\Functions\Functions.lua:41
 HideHighlightActionButton = <function> defined @Interface\AddOns\AsphyxiaU

**Comment by Bloodb** [comment]
It occurs when I use Rebuke.

**Comment by sinaris** [comment]
Thanks. Fixed now.
https://github.com/sinaris/AsphyxiaUI---v6/commit/047c6cea08e26cbcccd950dd351e389e5d5f9bb1
